baseURL = "https://ben9583.com"
title = "Ben Plate"
theme = "gokarna"
defaultContentLanguage = "en"
languageCode = "en"
enableEmoji = true

# Automatically generate robots.txt
enableRobotsTXT = true

[params]
  footer = "Ben Plate"
  description = "Software Engineer, CS Student @ UC Berkeley"
  avatarURL = "/images/avatar.webp"
  aboutImage = "/images/about/ben_about.webp"
  aboutImageDescription = "Me at Berkeley"
  avatarSize = "size-xl"
  customHeadHTML = """
    <meta name="google-site-verification" content="yichU42T6JR2md_yblNykpuTZ7FBd8R5lb6u7T5yqxE" />
    <meta name="theme-color" content="#22272e" />
    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
    <link rel="manifest" href="manifest.json" />
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-MF4SZ5V35G"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-MF4SZ5V35G');
    </script>
    <!-- KaTeX -->
    <link rel="preload" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css" as="style" crossorigin="anonymous" onload="this.onload=null;this.rel='stylesheet'">
    <noscript><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css" crossorigin="anonymous"></noscript>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js" crossorigin="anonymous"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js" onload="renderMathInElement(document.body, { delimiters: [{left: '$$', right: '$$', display: true}, {left: '$', right: '$', display: false}]});" crossorigin="anonymous"></script>
  """
  socialIcons = [
    {name = "linkedin", url = "https://linkedin.com/in/benplate"},
    {name = "github", url = "https://github.com/ben9583"},
    {name = "email", url = "mailto:bplate9583@gmail.com"}
  ]
  metaKeywords = ["Ben Plate", "ben9583", "Software Engineer", "Developer", "Student", "UC Berkeley", "blog"]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    pre = "<span data-feather='user'></span>"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 4

  [[menu.main]]
    name = "Resume"
    pre = "<span data-feather='file-text'></span>"
    url = "/resumes/resume.pdf"
    weight = 5

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 6

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 8

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false