baseURL = "https://ben9583.com"
title = "Ben Plate"
theme = "gokarna"
defaultContentLanguage = "en"
languageCode = "en"
enableEmoji = true

# Automatically generate robots.txt
enableRobotsTXT = true

[params]
  footer = "Ben Plate"
  description = "Software Engineer, CS Student @ UC Berkeley"
  avatarURL = "/images/avatar.webp"
  aboutImage = "/images/about/ben_asian_ghetto.webp"
  aboutImageDescription = "Me at Berkeley's \"Asian Ghetto\""
  avatarSize = "size-xl"
  customHeadHTML = """
    <meta name="google-site-verification" content="yichU42T6JR2md_yblNykpuTZ7FBd8R5lb6u7T5yqxE" />
    <meta name="theme-color" content="#22272e" />
    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
    <link rel="manifest" href="manifest.json" />
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-MF4SZ5V35G"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-MF4SZ5V35G');
    </script>
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous" />
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """
  socialIcons = [
    {name = "linkedin", url = "https://linkedin.com/in/benplate"},
    {name = "github", url = "https://github.com/ben9583"},
    {name = "email", url = "mailto:bplate9583@gmail.com"}
  ]
  metaKeywords = ["Ben Plate", "ben9583", "Software Engineer", "Developer", "Student", "UC Berkeley", "blog"]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    pre = "<span data-feather='user'></span>"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 4

  [[menu.main]]
    name = "Resume"
    pre = "<span data-feather='file-text'></span>"
    url = "/resumes/resume.pdf"
    weight = 5

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 6

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/ben9583"
    weight = 7

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 8

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false